<?php

/**
 * @file
 * Provides integration with Braintree Drop-in UI.
 */

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_braintree_dropin_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['braintree_dropin'] = array(
    'base' => 'commerce_braintree_dropin',
    'title' => t('Braintree Drop-in UI'),
    'short_title' => t('Braintree Drop-in UI'),
    'display_title' => t('Credit card'),
    'description' => t('Integrates with Braintree Drop-in for secure on-site credit card payment.'),
    'terminal' => TRUE,
    'offsite' => FALSE,
    'cardonfile' => array(
      'create callback' => 'commerce_braintree_dropin_cardonfile_form_submit',
      'create form callback' => 'commerce_braintree_dropin_cardonfile_form',
      'update callback' => 'commerce_braintree_dropin_cardonfile_form_submit',
      'update form callback' => 'commerce_braintree_dropin_cardonfile_form',
      'delete callback' => 'commerce_braintree_dropin_cardonfile_delete',
    ),
  );

  return $payment_methods;
}

/**
 * Payment method callback: Braintree Drop-in UI settings form.
 *
 * @see CALLBACK_commerce_payment_method_settings_form()
 */
function commerce_braintree_dropin_settings_form($settings = array()) {
  // Reuse the transparent redirect settings form.
  return commerce_braintree_tr_settings_form($settings);
}

/**
 * Implements hook_form_alter().
 */
function commerce_braintree_dropin_form_alter(&$form, &$form_state, $form_id) {
  // Check to see if this is a checkout form and there is payment form element.
  if (strstr($form_id, 'commerce_checkout_form')
      && !empty($form['commerce_payment'])
      && !empty($form_state['order']->payment_methods)) {

    // Determine if Braintree Drop-in is available for this order.
    $payment_methods = $form_state['order']->payment_methods;
    foreach ($payment_methods as $payment_method) {
      if ($payment_method['method_id'] == 'braintree_dropin') {
        $drop_in = TRUE;
      }
    }

    if (!empty($drop_in)) {
      // Make sure the Drop-in javascript api is included.
      $form['#attached']['js'][] = array(
        'data' => 'https://js.braintreegateway.com/v2/braintree.js',
        'type' => 'external',
      );

      // When there is more than 1 payment method available, replace the
      // ajax handler for the payment method selector so that the entire
      // form is reloaded. Otherwise you cannot switch between different
      // payment methods during checkout. This is because Braintree
      // Drop-in hijacks the form event handlers.
      if (count($payment_methods) > 1) {
        $form['#prefix'] = '<div id="commerce-braintree-dropin-checkout-wrapper">';
        $form['#suffix'] = '</div>';
        $form['commerce_payment']['payment_method']['#ajax'] = array(
          'callback' => 'commerce_braintree_dropin_checkout_ajax',
          'wrapper' => 'commerce-braintree-dropin-checkout-wrapper',
        );
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alters the admin order payment form to add support for Braintree Drop-in UI.
 */
function commerce_braintree_dropin_form_commerce_payment_order_transaction_add_form_alter(&$form, &$form_state) {
  // Make sure the Drop-in javascript api is included.
  $form['#attached']['js'][] = array(
    'data' => 'https://js.braintreegateway.com/v2/braintree.js',
    'type' => 'external',
  );

  // Include the Braintree Drop-in UI when it is selected as the payment method.
  if (!empty($form['payment_terminal']) && $form_state['payment_method']['method_id'] == 'braintree_dropin') {

    $arguments = array();
    if (!empty($form_state['order']->uid)) {
      $account = user_load($form_state['order']->uid);
      if (!empty($account->data['braintree_vault']['id'])) {
        $arguments['customerId'] = $account->data['braintree_vault']['id'];
      }
    }

    $form['payment_terminal']['payment_details'] += (array) commerce_braintree_dropin_submit_form_elements($form_state['payment_method'], $arguments);

    // Determine the default submit for settlement option for this payment method.
    if (isset($form_state['payment_method']['settings']['submit_for_settlement'])) {
      $submit_for_settlement = (bool) $form_state['payment_method']['settings']['submit_for_settlement'];
    }
    else {
      $submit_for_settlement = TRUE;
    }

    // Add the ability to submit for settlement or just authorize the transaction.
    $form['payment_terminal']['payment_details']['submit_for_settlement'] = array(
      '#type' => 'checkbox',
      '#title' => t('Submit the transaction for settlement?'),
      '#default_value' => $submit_for_settlement,
      '#description' => t('If unchecked the payment will have to be settled manually at a later date.'),
    );
  }
}

/**
 * Override of commerce_payment_pane_checkout_form_details_refresh().
 *
 * Replaces the entire form so that Braintree Drop-in events can be
 * added or removed properly when changing payment methods during
 * checkout.
 */
function commerce_braintree_dropin_checkout_ajax(&$form, &$form_state) {
  return $form;
}

/**
 * Form callback for Braintree Drop-in payment method.
 *
 * @see CALLBACK_commerce_payment_method_submit_form().
 */
function commerce_braintree_dropin_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  $form = array();

  $arguments = array();
  if (!empty($order->uid)) {
    $account = user_load($order->uid);
    if (!empty($account->data['braintree_vault']['id'])) {
      $arguments['customerId'] = $account->data['braintree_vault']['id'];
    }
  }

  // Append common the drop-in ui form elements to the form array.
  $form += (array) commerce_braintree_dropin_submit_form_elements($payment_method, $arguments);

  return $form;
}

/**
 * Validation callback for the Braintree Drop-in payment method.
 *
 * @see CALLBACK_commerce_payment_method_submit_form_validate().
 */
function commerce_braintree_dropin_submit_form_validate($payment_method, $pane_form, &$pane_values, $order, $charge) {
  // Make sure we have a valid nonce (sale token) returned from Braintree.
  $nonce = commerce_braintree_dropin_get_nonce();
  if (empty($nonce)) {
    form_set_error('braintree_dropin', t('We were unable to charge your card at this time.'));
    return FALSE;
  }
}

/**
 * Submit callback for the Braintree Drop-in payment method.
 *
 * @see CALLBACK_commerce_payment_method_submit_form_submit()
 */
function commerce_braintree_dropin_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {
  $nonce = commerce_braintree_dropin_get_nonce();
  commerce_braintree_initialize($payment_method);

  list($amount, $customer_name, $first_name, $last_name, $country, $thoroughfare, $locality, $postal_code, $administrative_area, $customer_mail) = _commerce_braintree_get_transaction_informations($order);

  $merchant_account_id = commerce_braintree_get_merchant_account_id($payment_method, $charge['currency_code']);

  // Determine if we should settle the transaction immediately.
  if (isset($pane_values['submit_for_settlement'])) {
    // Allows the admin payment transaction terminal to override the default.
    $submit_for_settlement = $pane_values['submit_for_settlement'];
  }
  elseif (isset($payment_method['settings']['submit_for_settlement'])) {
    // Use the payment method settings.
    $submit_for_settlement = (bool) $payment_method['settings']['submit_for_settlement'];
  }
  else {
    // Default to TRUE if this setting hasn't been explicitly set by the store admin.
    $submit_for_settlement = TRUE;
  }

  $sale_data = array(
    'amount' => commerce_braintree_price_amount($charge['amount'], $charge['currency_code']),
    'orderId' => $order->order_id,
    'channel' => 'CommerceGuys_BT_Vzero',
    'merchantAccountId' => $merchant_account_id,
    'paymentMethodNonce' => $nonce,
    'customer' => array(
      'firstName' => $first_name,
      'lastName' => $last_name,
      'email' => $customer_mail,
    ),
    'billing' => array(
      'countryCodeAlpha2' => $country,
      'streetAddress' => $thoroughfare,
      'firstName' => $customer_name,
      'locality' => $locality,
      'postalCode' => $postal_code,
      'region' => $administrative_area,
    ),
    'options' => array(
      'storeInVault' => !empty($pane_values['cardonfile']) ? TRUE : FALSE,
      'submitForSettlement' => $submit_for_settlement,
    ),
  );

  // Allow other modules to alter the sale before sending it to Braintree.
  drupal_alter('commerce_braintree_dropin_sale_data', $sale_data, $order);

  // Execute the API sale method to create a sale object.
  $response = Braintree_Transaction::sale($sale_data);

  // Process the Braintree response and create a payment transaction.
  $transaction = commerce_braintree_dropin_process_transaction($order, $payment_method, $charge, $response);

  // Set a form error if the payment transaction failed for any reason.
  if (empty($transaction->status) || !in_array($transaction->status, array(COMMERCE_PAYMENT_STATUS_SUCCESS, COMMERCE_PAYMENT_STATUS_PENDING))) {
    $error = t('Your payment transaction could not be processed at this time. If an error was provided it was: @response', array('@response' => $response->message));

    // Allow other modules to customize the error that's displayed ot customers.
    drupal_alter('commerce_braintree_transaction_error', $error, $transaction, $response);
    form_set_error('braintree_dropin', $error);
    return FALSE;
  }

  // Save the Braintree vault information to the customer.
  if (!empty($pane_values['cardonfile'])) {
    commerce_braintree_dropin_create_cardonfile($order, $payment_method, $response);
  }

  return TRUE;
}

/**
 * Returns the common FAPI form elements for all Drop-in UI implementations.
 *
 * @param $payment_method
 *   The payment method being used.
 * @param array $arguments
 *   An array of arguments to be passed Braintree token method.
 *
 * @return array
 *   An array of form elements for the drop-in ui.
 */
function commerce_braintree_dropin_submit_form_elements($payment_method, $arguments = array()) {
  global $user;
  $form = array();

  // Initialize Braintree and create a token.
  commerce_braintree_initialize($payment_method);
  $token = Braintree_ClientToken::generate($arguments);

  // The custom token is required to generate the Drop-in payment form.
  $form['#attached']['js'][] = array(
    'data' => array('commerceBraintreeDropinToken' => $token),
    'type' => 'setting',
  );

  // Attach our own javascript to handle the Drop-in form generation.
  $form['#attached']['js'][] = drupal_get_path('module', 'commerce_braintree_dropin') . '/js/commerce_braintree_dropin.js';

  // Include a container div for the Drop-in form to attach to.
  $form['braintree_dropin'] = array(
    '#markup' => '<div id="commerce-braintree-dropin-container"></div>',
  );

  // Add option to save card on file for authenticated users.
  if (!empty($payment_method['settings']['cardonfile']) && !empty($user->uid)) {
    $storage = variable_get('commerce_cardonfile_storage', 'opt-in');
    if ($storage !== 'required') {
      $form['cardonfile'] = array(
        '#type' => 'checkbox',
        '#title' => t('Securely save this payment method for next time.'),
        '#default_value' => $storage == 'opt-in' ? FALSE : TRUE,
      );
    }
    else {
      $form['cardonfile'] = array(
        '#type' => 'value',
        '#value' => TRUE,
      );
    }
  }

  return $form;
}

/**
 * Save a commerce_payment_transaction object from the drop-in response.
 */
function commerce_braintree_dropin_process_transaction($order, $payment_method, $charge, $response) {
  // Determine the charge amount from the response object.
  $amount = $response->transaction->_attributes['amount'];
  $currency_code = $response->transaction->_attributes['currencyIsoCode'];
  $amount_converted = commerce_currency_decimal_to_amount($amount, $currency_code);

  // Determine the payment transaction internal status from the response status.
  $remote_status = !empty($response->transaction->_attributes['status']) ? $response->transaction->_attributes['status'] : NULL;
  $transaction = commerce_payment_transaction_new('braintree_dropin', $order->order_id);
  $transaction->instance_id = $payment_method['instance_id'];
  $transaction->remote_id = !empty($response->transaction->_attributes['id']) ? $response->transaction->_attributes['id'] : NULL;
  $transaction->amount = $amount_converted;
  $transaction->currency_code = $currency_code;
  $transaction->payload[REQUEST_TIME] = $response;
  $transaction->status = commerce_braintree_transaction_status($remote_status);
  $transaction->remote_status = $remote_status;
  $transaction->message = commerce_braintree_build_payment_transaction_message($response);
  commerce_payment_transaction_save($transaction);
  return $transaction;
}

/**
 * Save a cardonfile entity from the drop-in response.
 */
function commerce_braintree_dropin_create_cardonfile($order, $payment_method, $response) {
  $attributes = !empty($response->transaction->_attributes) ? $response->transaction->_attributes : array();

  // Do not attempt to save a card on file if there was no token returned or
  // the order owner is anonymous.
  if (empty($attributes['creditCard']['token']) || empty($order->uid)) {
    return FALSE;
  }

  $token = $attributes['creditCard']['token'];

  // Attempt to load an existing card on file with the same token before
  // creating a new one.
  $cards = commerce_cardonfile_load_multiple(FALSE, array('remote_id' => $token));
  if (!empty($cards)) {
    $cardonfile = reset($cards);
  }
  else {
    $cardonfile = commerce_cardonfile_new();
  }

  // Populate all of the cardonfile properties from the response object.
  $cardonfile->card_name = $attributes['customer']['firstName'] . ' ' . $attributes['customer']['lastName'];
  $cardonfile->card_type = $attributes['creditCard']['cardType'];
  $cardonfile->card_exp_month = $attributes['creditCard']['expirationMonth'];
  $cardonfile->card_exp_year = $attributes['creditCard']['expirationYear'];
  $cardonfile->card_number = $attributes['creditCard']['last4'];
  $cardonfile->payment_method = $payment_method['method_id'];
  $cardonfile->instance_id = $payment_method['instance_id'];
  $cardonfile->instance_default = TRUE;
  $cardonfile->uid = $order->uid;
  $cardonfile->remote_id = $attributes['creditCard']['token'];
  $cardonfile->status = TRUE;

  commerce_cardonfile_save($cardonfile);

  // Save the Braintree vault data to the user profile.
  $user = user_load($order->uid);
  $user->data['braintree_vault'] = $attributes['customer'];
  user_save($user);
}

/**
 * Gets the payment_method_nonce from the post variables if it exists.
 */
function commerce_braintree_dropin_get_nonce() {
  return !empty($_POST['payment_method_nonce']) ? check_plain($_POST['payment_method_nonce']) : NULL;
}

/**
 * Form callback for commerce_cardonfile entities.
 */
function commerce_braintree_dropin_cardonfile_form($form, &$form_state, $op, $card) {
  $form_state['card'] = $card;
  $account = user_load($card->uid);
  $arguments = array();
  $payment_instance = commerce_payment_method_instance_load($card->instance_id);
  $form_state['payment_instance'] = $payment_instance;
  commerce_braintree_initialize($payment_instance);

  if (!empty($card->remote_id)) {
    // Query Braintree for the payment method matching this card on file.
    try {
      $payment_method = \Braintree_PaymentMethod::find($card->remote_id);
    }
    catch (Exception $ex) {
      // If Braintree doesn't return the payment method, we cannot proceed.
      drupal_set_message(t('We are unable to locate your stored payment method'), 'error');
      watchdog('commerce_braintree_dropin', 'Unable to fetch Braintree payment method due to @error', array('@error' => $ex->getMessage()), WATCHDOG_ERROR);
      return array();
    }
  }

  // Determine the Braintree customer id and append it to the API request.
  if (!empty($account->data) && !empty($account->data['braintree_vault'])) {
    // Set the Braintree Customer ID if stored on the user object.
    $arguments['customerId'] = $account->data['braintree_vault']['id'];
  }
  else if (!empty($payment_method->customerId)) {
    // Set the Braintree Customer ID from the loaded payment method.
    $arguments['customerId'] = $payment_method->customerId;
  }

  // Append common the drop-in ui form elements to the form array.
  $form += (array) commerce_braintree_dropin_submit_form_elements($payment_instance, $arguments);

  // Remove the card on file options since we're always saving these.
  unset($form['cardonfile']);

  // Make sure the Drop-in javascript api is included.
  $form['#attached']['js'][] = array(
    'data' => 'https://js.braintreegateway.com/v2/braintree.js',
    'type' => 'external',
  );

  $form['customer_id'] = array(
    '#type' => 'value',
    '#value' => !empty($arguments['customerId']) ? $arguments['customerId'] : FALSE,
  );

  $form['actions'] = array(
    '#type' => 'container',
  );

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save Payment Method'),
  );

  return $form;
}

/**
 * Submit handler for commerce_cardonfile form callbacks.
 */
function commerce_braintree_dropin_cardonfile_form_submit(&$form, &$form_state) {
  $account = user_load($form_state['card']->uid);
  $cards = commerce_cardonfile_load_multiple_by_uid($form_state['card']->uid, $form_state['payment_instance']['instance_id']);
  commerce_braintree_initialize($form_state['payment_instance']);
  $nonce = commerce_braintree_dropin_get_nonce();

  // Populate the customer variable with data from Braintree.
  if (!empty($form_state['values']['customer_id'])) {
    // Query for the customer record from the customer id in form values.
    try {
      $customer = Braintree_Customer::find($form_state['values']['customer_id']);
    }
    catch (Exception $ex) {
      watchdog('commerce_braintree_dropin', 'Unable to fetch Braintree customer account due to @error', array('@error' => $ex->getMessage()), WATCHDOG_ERROR);
      return;
    }

    // Create or determine the payment method that was selected
    // during update.
    try {
      $payment_method = Braintree_PaymentMethod::create(array(
        'customerId' => $form_state['values']['customer_id'],
        'paymentMethodNonce' => $nonce,
      ))->paymentMethod;
    } catch (Exception $ex) {
      watchdog('commerce_braintree_dropin', 'Unable to load/create a payment method due to @error', array('@error' => $ex->getMessage()), WATCHDOG_ERROR);
      return;
    }
  }
  else {
    // Create a new customer and payment method at once.
    try {
      $customer = Braintree_Customer::create(array(
        'email' => $account->mail,
        'paymentMethodNonce' => $nonce,
      ))->customer;
      $payment_method = reset($customer->creditCards);
    }
    catch (Exception $ex) {
      watchdog('commerce_braintree_dropin', 'Unable to fetch Braintree customer account due to @error', array('@error' => $ex->getMessage()), WATCHDOG_ERROR);
      return;
    }
  }

  try {
    if (!empty($payment_method->token)) {
      // Set this payment method as the default.
      Braintree_PaymentMethod::update($payment_method->token, array('options' => array('makeDefault' => TRUE)));
      $instance_default = $payment_method->token;
    }
  }
  catch (Exception $ex) {
    watchdog('commerce_braintree_dropin', 'Unable to set default payment method due to @error', array('@error' => $ex->getMessage()), WATCHDOG_ERROR);
  }

  // Loop over each of the Braintree payment methods and make sure
  // a matching card on file entity exits.
  foreach ($customer->creditCards as $vault_profile) {
    $card = commerce_cardonfile_load_multiple(array(), array('remote_id' => $vault_profile->token));

    // Create a new card on file entity if we were unable to load one
    // for this vault profile.
    if (empty($card)) {
      $card = commerce_cardonfile_new();
      $card->remote_id = $vault_profile->token;
      $card->status = TRUE;
      $card->uid = $form_state['card']->uid;
    }
    else {
      $card = reset($card);
    }

    // Update the values returned from Braintree.
    $card->card_type = $vault_profile->cardType;
    $card->card_number = $vault_profile->last4;
    $card->card_exp_month = $vault_profile->expirationMonth;
    $card->card_exp_year = $vault_profile->expirationYear;
    $card->instance_default = $vault_profile->default;
    $card->payment_method = $form_state['payment_instance']['method_id'];
    $card->instance_id = $form_state['payment_instance']['instance_id'];
    $card->instance_default = !empty($instance_default) ? ($instance_default == $vault_profile->token) : $vault_profile->default;

    commerce_cardonfile_save($card);

    // Pop this card off the cards on file array.
    unset($cards[$card->card_id]);
  }

  // Loop over any cards that were't returned from Braintree
  // and make sure they're deleted.
  foreach ($cards as $card) {
    commerce_cardonfile_delete($card->card_id);
  }

  // Store the Braintree customer information on the Drupal user.
  $account->data['braintree_vault']['id'] = $customer->id;
  user_save($account);

  drupal_set_message(t('Payment information updated successfully'));
  $form_state['redirect'] = 'user/' . $form_state['card']->uid . '/cards';
}

/**
 * Delete callback for commerce_cardonfile.
 */
function commerce_braintree_dropin_cardonfile_delete($form, &$form_state, $payment_method, $card) {
  commerce_braintree_initialize($payment_method);
  try {
    Braintree_PaymentMethod::delete($card->remote_id);
  }
  catch (Exception $ex) {
    watchdog('commerce_braintree_dropin', 'Unable to delete payment method due to @error', array('@error' => $ex->getMessage()), WATCHDOG_ERROR);
    drupal_set_message(t('Unable to delete the payment method at this time'), 'error');
  }

  // If the card being deleted is the instance default, attempt to update
  // another card owned by the the same user as the instance default.
  if ($card->instance_default) {
    $cards = commerce_cardonfile_load_multiple_by_uid($card->uid, $payment_method);
    unset($cards[$card->card_id]);
    if (!empty($cards)) {
      $new_default = reset($cards);
      $new_default->instance_default = TRUE;
      commerce_cardonfile_save($new_default);
    }
  }

  commerce_cardonfile_delete($card->card_id);

  return TRUE;
}
